import FormData from "form-data";
import { getCSRF, readPromise, getVerificationToken, getUserId } from "./util.js";
import path from "path";

export default class UploaderApi {
    readonly token:string;

    constructor(token:string) {
        this.token = token;
    }

    /**
     * 
     * @param {string} filepath
     * @param {string} name
     * @description Uploads T-Shirt to Roblox and returns its assetID
     * @returns Promise<number>
     */

    async UploadTShirt(filepath:string,name:string) {
        return new Promise(async (resolve,reject) => {
            let form = new FormData()
            
            let veritoken = await getVerificationToken("https://www.roblox.com/build/upload?assetTypeId=2",this.token)

            if (!veritoken.header) { reject("no"); return }

            // I essentially almost gave up here, sorry for the bad code
            
            form.append("assetTypeId",2)
            form.append("file",await readPromise(filepath),{filename:path.basename(filepath),contentType:`image/${path.basename(filepath).split(".")[path.basename(filepath).split(".").length-1].toLowerCase()}`})
            form.append("config",Buffer.from(JSON.stringify({
                name:name,
                description:"Autogenerated via AvatarServer",
                creatorTargetId:await getUserId(this.token),
                creatorType:"User"
            })),{filename:"config.json",contentType:"application/json"})
            form.append("name",name)
            form.append("groupId",'')
            form.append("__RequestVerificationToken",veritoken.input)
            
            form.submit({
                host:"itemconfiguration.roblox.com",
                path:"/v1/avatar-assets/2/upload",
                protocol:"https:",
                headers:{
                    Cookie: `.ROBLOSECURITY=${this.token};__RequestVerificationToken=${veritoken.header[1]};`,
                    "X-CSRF-Token":await getCSRF(this.token),
                    "Referer":"https://www.roblox.com/build/upload?AssetTypeId=2&GroupId="
                },
                method:"POST"
            },(err,res) => {
                if (err) {reject(err)}
                if (!res) {reject(new Error("no res"));return}
                let data = ""
                res.on("error",(e) => {
                    reject(e)
                })
                res.on("data",(chunk) => {
                    data += chunk
                })
                res.on("end",() => {
                    if (res.statusCode == 200) {
                       resolve(JSON.parse(data).assetId)
                    } else {
                        reject(new Error(`${res.statusCode} ${res.statusMessage}: ${data}`))
                    }
                })
            })
        })
    }
}